language: python

python:
    #- 2.7
    - 3.3
    - 3.5

notifications:
  email:
    on_success: never # default: change
    on_failure: always

#services: 
#    - mysql
#    - postgresql

env:
    - DJANGO=1.8.4 DB=mysql
    - DJANGO=1.8.4 DB=postgresql
    - DJANGO=1.9 DB=postgresql
    - DJANGO=1.9 DB=mysql

matrix:
    exclude:
        - python: 3.3
          env: DJANGO=1.9 DB=mysql
        - python: 3.3
          env: DJANGO=1.9 DB=postgresql
      
before_install:
  #- export DEBUG=true
  #- export PYTHONPATH=$HOME/builds/your_github_username/your_repo
  - export DJANGO_SETTINGS_MODULE=siaad.settings
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  #- pip install psycopg2 --quiet

before_script:
  #- mysql -e 'create database travis;' -u travis
    - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS travis_ci_test;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS travis_ci_test;' -uroot; fi"
    - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database travis_ci_test;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database travis_ci_test;' -uroot; fi"

script:
    # exclude Python 3.3 and Django >= 1.9, python = 3.3 it's not supported
    - python manage.py makemigrations --noinput
    - python manage.py migrate --noinput
