language: python

python:
  - 2.7
  - 3.3
  - 3.5

notifications:
  email:
    on_success: never # default: change
    on_failure: always

services: 
    - mysql
    - postgresql

env:
    - DJANGO=1.8.4 DB=postgresql
    - DJANGO=1.8.4 DB=postgresql
    - DJANGO=1.9 DB=mysql
    - DJANGO=1.9 DB=mysql
      
before_install:
  #- export DEBUG=true
  #- export PYTHONPATH=$HOME/builds/your_github_username/your_repo
  - export DJANGO_SETTINGS_MODULE=siaad.settings
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  #- pip install psycopg2 --quiet

before_script:
  #- mysql -e 'create database travis;' -u travis
    - mysql -e "create database IF NOT EXISTS test;" -uroot
    - psql -c 'create database travis_ci_test;' -U postgres

script:
    - python manage.py makemigrations --noinput
    - python manage.py migrate --noinput
