# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamentos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraModificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('cambioDe', models.CharField(blank=True, max_length=30)),
                ('cambioA', models.CharField(max_length=30)),
                ('cambioTabla', models.CharField(max_length=30)),
                ('fk_departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Departamentos.Departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuario')),
            ],
        ),
    ]
